# fly.toml app configuration file generated for podcastthing23 on 2023-10-14T23:28:41+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "podcastthing23"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = true
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"